config/routes.rb
Rails.application.routes.draw do
  resources :fillin_card_tests
  resources :fillin_tests
  resources :fillin_categories
  resources :fillin_domains
  resources :fillin_cards
  root to: 'main#index'
  resources :cards_tests
  resources :tests do
    member do
      get 'create_on_incorrect'
    end
    collection do
      get 'combine_new'
      post 'combine_create'
    end
  end
  resources :cards
  resources :categories
  resources :domains
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<h1 class=" text-center text-primary">FlashCards</h1>

<div class="text-center">
  <%= link_to 'Tests', tests_path, class: 'btn btn-lg btn-primary'%>
</div>

<br>

<div class="row">
  <%= link_to 'Domains', domains_path, class: 'col-sm-6 btn btn-info'%>
  <%= link_to 'Categories', categories_path, class: 'col-sm-6 btn btn-info'%>
</div>


<table class="table">
  <thead>
    <tr>
      <th>Domains</th>
      <th>Categories</th>
    </tr>
  </thead>

  <tbody>
    <% Domain.all.each do |domain| %>
      <tr>
        <td>
          <h2><%= domain.name %> </h2>
          <%= link_to "+ Add Category within Domain", new_category_path(domain_id: domain), class: 'btn btn-sm btn-success' %>
        </td>
        <td>
          <% domain.categories.each do |cat|%>
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-sm table-borderless table-hover">
                    <tbody>
                      <tr>
                        <td>
                          <span class="badge badge-pill badge-info"><%= cat.cards.size%> </span> <%= link_to cat.name, category_path(cat) %>
                        </td>
                        <td>
                          <%= link_to "+ Add Card", new_card_path(domain_id: domain, category_id: cat), class: "btn btn-sm btn-success float-right" %>
                        </td>
                      </tr>
                    </tbody>
                  </table>
              </div>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>