config/routes.rb
Rails.application.routes.draw do
  resources :fillin_card_tests
  resources :fillin_tests
  resources :fillin_categories
  resources :fillin_domains
  resources :fillin_cards
  root to: 'main#index'
  resources :cards_tests
  resources :tests do
    member do
      get 'create_on_incorrect'
    end
    collection do
      get 'combine_new'
      post 'combine_create'
    end
  end
  resources :cards
  resources :categories
  resources :domains
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fillin_domain.rb
class FillinDomain < ApplicationRecord
  has_many :fillin_cards, dependent: :destroy
  has_many :fillin_categories, dependent: :destroy
end

app/models/fillin_test.rb
class FillinTest < ApplicationRecord
  attr_accessor :fillin_category_ids
  has_many :fillin_card_tests, dependent: :destroy
  has_many :fillin_cards, through: :fillin_card_tests

  accepts_nested_attributes_for :fillin_card_tests


  def fillin_cards_correct
    count = 0
    fillin_card_tests.each {|fct| count += 1 if fct.correct? }
    count
  end

  def fillin_total_cards
    fillin_card_tests.size
  end

  def test_not_started?
    return true if fillin_card_tests.all? {|fct| fct.correct.nil?}
  end

  def completed?
    return true if fillin_card_tests.all? {|fct| fct.correct != nil }
  end

  def at_least_one_card_incorrect?
    return if !completed?
    return true if fillin_card_tests.any? {|fct| fct.correct == false }
  end

  def generate_next_question
    fillin_card_tests.unanswered.to_a.shuffle.first
  end

  def all_answered?
    fillin_card_tests.all?(&:answered?)
  end
end

app/controllers/fillin_tests_controller.rb
class FillinTestsController < ApplicationController
  before_action :set_fillin_test, only: %i[ show edit update destroy ]

  # GET /fillin_tests or /fillin_tests.json
  def index
    @fillin_tests = FillinTest.all.includes(fillin_card_tests: [:fillin_card_answers, fillin_card: [:fillin_domain, :fillin_category]])
  end

  # GET /fillin_tests/1 or /fillin_tests/1.json
  def show
  end

  # GET /fillin_tests/new
  def new
    @fillin_test = FillinTest.new
  end

  # GET /fillin_tests/1/edit
  def edit
  end

  # POST /fillin_tests or /fillin_tests.json
  def create
    @fillin_test = FillinTest.new(fillin_test_new_params)

    respond_to do |format|
      if @fillin_test.save

        # pull in all the cards for that category in order to make a test
        if params[:fillin_test][:fillin_category_ids].reject(&:empty?).any?
          params[:fillin_test][:fillin_category_ids].reject(&:empty?).each do |cat_id|
            FillinCategory.find(cat_id).fillin_cards.each do |fillin_card|
              @fillin_test.fillin_card_tests.build(fillin_card: fillin_card).save
            end
          end
        end

        # The fillin cards exist. Now create all the answers and by default "Hide" teh answer so it has to be filled in
        @fillin_test.fillin_card_tests.each do |fillin_card_test|
          fillin_card_test.fillin_card.fillin_card_answers.each do |fillin_answer|
            FillinCardTestUserAnswer.new(fillin_card_test_id: fillin_card_test.id, fillin_card_answer_id: fillin_answer.id, hidden: true).save
          end
        end

        format.html { redirect_to edit_fillin_test_path(@fillin_test), notice: "Specify which portions of each card to show/hide." }
        format.json { render :show, status: :created, location: @fillin_test }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fillin_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fillin_tests/1 or /fillin_tests/1.json
  def update
    respond_to do |format|
      if @fillin_test.update(fillin_test_edit_params)
        format.html { redirect_to @fillin_test, notice: "Fillin test was successfully created." }
        format.json { render :show, status: :ok, location: @fillin_test }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fillin_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fillin_tests/1 or /fillin_tests/1.json
  def destroy
    @fillin_test.destroy

    respond_to do |format|
      format.html { redirect_to fillin_tests_url, notice: "Fillin test was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fillin_test
      @fillin_test = FillinTest.includes(fillin_card_tests: [:fillin_card_answers, fillin_card: [:fillin_domain, :fillin_category]]).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fillin_test_new_params
      params.require(:fillin_test).permit(:name, :fillin_category_ids)
    end

    def fillin_test_edit_params
      params.require(:fillin_test).permit(:name, :fillin_category_ids)
      params.require(:fillin_test).permit(fillin_card_tests_attributes: [:id, fillin_card_test_user_answers_attributes: [:id, :hidden]])
    end
end

app/helpers/fillin_tests_helper.rb
module FillinTestsHelper
end

app/views/fillin_tests/_edit_form.html.erb
<%= form_with(model: fillin_test) do |form| %>
  <% if fillin_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fillin_test.errors.count, "error") %> prohibited this Fill-in test from being saved:</h2>

      <ul>
        <% fillin_test.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.fields_for :fillin_card_tests do |fillin_card_test_form| %>

    <div class="card">
      <div class="card-header"><strong>Card</strong></div>
      <div class="card-body">
        <%= custom_trix_safe(fillin_card_test_form.object.convert_to_question_display_completely_hidden)%>
      </div>
      <div class="card-footer">
        <div class="row">
          <%= fillin_card_test_form.fields_for :fillin_card_test_user_answers do |user_answer_form| %>
            <div class="col-5">
              <%= label_tag :hidden, "Hide Answer?" %><br>
                <%= user_answer_form.radio_button :hidden, '1', checked: user_answer_form.object.hidden? %>
                <%= user_answer_form.label :hidden, 'Yes', value: "1" %>
                <%= user_answer_form.radio_button :hidden, '0', checked: !user_answer_form.object.hidden? %>
                <%= user_answer_form.label :hidden, 'No', value: "0" %>
            </div>
            <div class="col-7">
              <%= label_tag :displayed_answer, "Q#{user_answer_form.object.fillin_card_answer.position}: " %>
              <p readonly class="form-control"><%=sanitize(user_answer_form.object.fillin_card_answer.answer)%></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <br>

  <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fillin_tests/_form.html.erb
<%= form_with(model: fillin_test) do |form| %>
  <% if fillin_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fillin_test.errors.count, "error") %> prohibited this Fill-in test from being saved:</h2>

      <ul>
        <% fillin_test.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field col-sm-12">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <br>

  <h3 class='text-muted'>Select Categories. All cards within that category will be added</h3>
  <div class="field">
    <%= form.collection_check_boxes(:fillin_category_ids, FillinCategory.all, :id, :test_creation_selectbox_to_s) do |b| %>
      <span class="badge badge-pill badge-info"><%= b.object.fillin_cards.size%> </span>
      <%= b.check_box %>
      <%= b.label %>
      <br>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fillin_tests/edit.html.erb
<h1>New Fillin Test</h1>
<h2>Step #2: Select Portions of Each Card to Show/Hide</h2>

<%= render 'edit_form', fillin_test: @fillin_test %>

app/views/fillin_tests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tests <%= link_to '+ New Test', new_fillin_test_path, class: "btn btn-sm btn-success" %></h1>

<div id="accordion">

<% @fillin_tests.each do |fillin_test| %>

  <div class="card">
    <div class="card-header">
      <h3>
        <small class='badge badge-secondary'><%=fillin_test.fillin_total_cards%></small>
        &nbsp;&nbsp;
        <%= fillin_test.name%>
        &nbsp;&nbsp;
        <small>
        <a class="card-link" data-toggle="collapse" class="align-right" href="#collapse<%=fillin_test.id%>">
          (see results)
        </a>
        </small>

        <% unless fillin_test.test_not_started?%>
          <small><%= fillin_test.fillin_cards_correct %> out of <%= fillin_test.fillin_total_cards%> correct</small>
        <% end %>

      </h3>
      <% if fillin_test.fillin_cards.any? %>
        <%= link_to "Start/Restart Test", edit_fillin_card_test_path(fillin_test.fillin_card_tests.first, start_test: true), class: "btn btn-sm btn-info"%>
      <% end %>
      <%= link_to 'Destroy Test', fillin_test, class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>

      <% if fillin_test.completed? && fillin_test.at_least_one_card_incorrect?%>
        <% #link_to 'Create Test with Incorrect Cards', create_on_incorrect_test_path(test), class: "btn btn-sm btn-success" %>
      <% end %>
    </div>
    <div id="collapse<%=fillin_test.id%>" class="collapse" data-parent="#accordion">
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Domain</th>
              <th>Category</th>
              <th>Question</th>
              <th>User Answer</th>
              <th>Correct?</th>
            </tr>
          </thead>

          <tbody>
            <% fillin_test.fillin_card_tests.each do |fillin_card_test| %>
              <tr class="<%=fillin_card_answer_styling(fillin_card_test)%>">
                <td><%= fillin_card_test.fillin_card.fillin_domain.name %></td>
                <td><%= fillin_card_test.fillin_card.fillin_category.name %></td>
                <td><%= fillin_card_test.fillin_card.question %></td>
                <td>
                  <% fillin_card_test.fillin_card_test_user_answers.each_with_index do |user_answer, index|%>
                    <strong>Q<%=index + 1%></strong>
                    <% if user_answer.hidden? %>
                      <i>(hidden)</i>
                    <% end %>
                    :&nbsp;
                    <% if !user_answer.hidden?%>
                      <span><%=user_answer.user_answer%></span>
                    <% elsif user_answer.correct? %>
                      <span class='text-success'><%=user_answer.user_answer%></span>
                    <% else %>
                      <span class='text-danger'><%=user_answer.user_answer%></span>
                    <% end %>
                    <br>
                  <% end %>
                </td>
                <td><%= fillin_card_test.correct_to_s %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

<% end %>

</div>

app/views/fillin_tests/new.html.erb
<h1>New Fillin Test</h1>
<h2>Step #1: Select Categories of cards</h2>

<%= render 'form', fillin_test: @fillin_test %>

<%= link_to 'Back', fillin_tests_path %>

app/views/fillin_tests/show.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
  <% #link_to "Start/Restart Test", edit_cards_test_path(@test.cards_tests.first, start_test: true), class: "btn btn-info"%>
</div>

<h1>Test Name: <%= @fillin_test.name%></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Domain</th>
      <th>Category</th>
      <th>Raw Question Text</th>
      <th>Fillin Prompt(s)</th>
      <th>User Answer(s)</th>
      <th>Correct?</th>
    </tr>
  </thead>

  <tbody>
    <% @fillin_test.fillin_card_tests.each do |fillin_card_test| %>
      <tr>
        <td><%= fillin_card_test.fillin_card.fillin_domain.name %></td>
        <td><%= fillin_card_test.fillin_card.fillin_category.name %></td>
        <td><%= fillin_card_test.fillin_card.question %></td>
        <td>
          <% fillin_card_test.fillin_card_test_user_answers.each_with_index do |user_answer, i| %>
            <strong>Q<%=i + 1%></strong> <i><%="(hidden)" if user_answer.hidden?%></i>: <%= sanitize(user_answer.fillin_card_answer.answer) %><br>
          <% end %>
        </td>
        <td>
          <% if fillin_card_test.fillin_card_test_user_answers.any?(&:unanswered?) %>
            1+ Fillable prompts are unanswered
          <% else %>
            <% fillin_card_test.fillin_card_test_user_answers.each_with_index do |user_answer, i| %>
              <strong>Q<%=i + 1%></strong> <i><%="(pre-filled)" if !user_answer.hidden?%></i>: <%= user_answer.user_answer %><br>
            <% end %>
          <% end %>
        </td>
        <td><%= fillin_card_test.correct_to_s %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Back to all Fill-in Tests', fillin_tests_path, class: "btn btn-info" %>