config/routes.rb
Rails.application.routes.draw do
  resources :fillin_card_tests
  resources :fillin_tests
  resources :fillin_categories
  resources :fillin_domains
  resources :fillin_cards
  root to: 'main#index'
  resources :cards_tests
  resources :tests do
    member do
      get 'create_on_incorrect'
    end
    collection do
      get 'combine_new'
      post 'combine_create'
    end
  end
  resources :cards
  resources :categories
  resources :domains
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fillin_card.rb
class FillinCard < ApplicationRecord
  belongs_to :fillin_domain
  belongs_to :fillin_category
  has_many :fillin_card_answers, dependent: :destroy
  has_many :fillin_card_tests, dependent: :destroy

  has_rich_text :question
  has_rich_text :additional_info

  validate :proper_special_char_answers
  validate :at_least_one_answer

  # grabs all answer text in between "[= =]"
  def answers_ary
    question.to_s.scan(/\[\=\K[^\=\]]+/)
  end

  def callback_after_create_and_update
    fillin_card_answers.destroy_all
    fillin_card_tests.destroy_all
    answers_ary.each_with_index do |answer, i|
      FillinCardAnswer.create(fillin_card: self, position: i + 1, answer: answer)
    end
  end

  private

  def proper_special_char_answers
    if question.to_s.scan(/\[\=/).size != question.to_s.scan(/\=\]/).size
      errors.add(:_, 'Your "[=" does not equal your "=]"')
    end
  end

  def at_least_one_answer
    if question.to_s.scan(/\[\=\K[^\=\]]+/).size == 0
      errors.add(:_, 'You need at least one fillable answer (a.k.a, one "[==]" )')
    end
  end


end

app/controllers/fillin_cards_controller.rb
class FillinCardsController < ApplicationController
  before_action :set_fillin_card, only: %i[ show edit update destroy ]

  # GET /fillin_cards or /fillin_cards.json
  def index
  end

  # GET /fillin_cards/1 or /fillin_cards/1.json
  def show
  end

  # GET /fillin_cards/new
  def new
    @fillin_card = FillinCard.new(fillin_domain_id: params[:fillin_domain_id], fillin_category_id: params[:fillin_category_id])
  end

  # GET /fillin_cards/1/edit
  def edit
  end

  # POST /fillin_cards or /fillin_cards.json
  def create
    @fillin_card = FillinCard.new(fillin_card_params)

    respond_to do |format|
      if @fillin_card.save
        @fillin_card.callback_after_create_and_update
        format.html { redirect_to @fillin_card.fillin_category, notice: "Fill-in Card was successfully created." }
        format.json { render :show, status: :created, location: @fillin_card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fillin_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fillin_cards/1 or /fillin_cards/1.json
  def update
    respond_to do |format|
      if @fillin_card.update(fillin_card_params)
        @fillin_card.callback_after_create_and_update
        format.html { redirect_to fillin_card_url(@fillin_card), notice: "Fillin card was successfully updated." }
        format.json { render :show, status: :ok, location: @fillin_card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fillin_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fillin_cards/1 or /fillin_cards/1.json
  def destroy
    @fillin_card.destroy

    respond_to do |format|
      format.html { redirect_to @fillin_card.fillin_category, notice: "Fill-in Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fillin_card
      @fillin_card = FillinCard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fillin_card_params
      params.require(:fillin_card).permit(:additional_info, :question, :fillin_domain_id, :fillin_category_id)
    end
end

app/helpers/fillin_cards_helper.rb
module FillinCardsHelper
end

app/views/fillin_cards/_fillable_card_help.html.erb
<div class="alert alert-info">
  <strong>How it Works:</strong><br>
  <ul>
    <li>Fillable portions of a fill-in card are surrounded by <strong>[= =]</strong> symbols <i>(with the answer specified within the symbols)</i>.</li>
    <li>You can have multiple, fillable portions on the same card.</li>
    <li>When it comes time to create a test for your fillable cards, you specify at that time which of the fillable portions you wish to hide on each card.</li>
  </ul>
</div>

app/views/fillin_cards/_form.html.erb
<%= form_with(model: fillin_card) do |form| %>
  <% if fillin_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fillin_card.errors.count, "error") %> prohibited this Fill-in card from being saved:</h2>

      <ul>
        <% fillin_card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'fillable_card_help'%>

  <%= form.hidden_field :fillin_domain_id %>

  <div class="row">
    <div class="col-sm-6">
      <%= form.label :fillin_category_id, "Fillin Category" %>
      <%= form.collection_select :fillin_category_id, form.object.fillin_domain.fillin_categories.all.order(:name), :id, :name, {}, class: "form-control"%>
    </div>
  </div>

  <div class="field">
    <%= form.label :question, "Question" %>
    <%= form.rich_text_area :question, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :additional_info, "Additional Info" %>
    <%= form.rich_text_area :additional_info %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fillin_cards/edit.html.erb
<h1>Editing Fillin Card</h1>

<%= render 'form', fillin_card: @fillin_card %>

<%= link_to 'Show', @fillin_card %> |

<% if @fillin_card.persisted? %>
  <%= link_to 'Back to Fillin Category', fillin_category_path(@fillin_card.fillin_category) %>
<% else %>
  <%= link_to 'Back', fillin_cards_path %>
<% end %>

app/views/fillin_cards/index.html.erb
<h1 class=" text-center text-primary">Fill-in Cards</h1>

<div class="text-center">
  <%= link_to 'Tests', fillin_tests_path, class: 'btn btn-lg btn-primary'%>
</div>

<br>

<div class="row">
  <%= link_to 'Fill-in Domains', fillin_domains_path, class: 'col-sm-6 btn btn-info'%>
  <%= link_to 'Fill-in Categories', fillin_categories_path, class: 'col-sm-6 btn btn-info'%>
</div>


<table class="table">
  <thead>
    <tr>
      <th>Fill-in Domains</th>
      <th>Fill-in Categories</th>
    </tr>
  </thead>

  <tbody>
    <% FillinDomain.all.each do |domain| %>
      <tr>
        <td>
          <h2><%= domain.name %> </h2>
          <%= link_to "+ Add Category within Domain", new_fillin_category_path(fillin_domain_id: domain), class: 'btn btn-sm btn-success' %>
        </td>
        <td>
          <% domain.fillin_categories.order(:name).each do |cat|%>
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-sm table-borderless table-hover">
                    <tbody>
                      <tr>
                        <td>
                          <span class="badge badge-pill badge-info"><%= cat.fillin_cards.size%> </span> <%= link_to cat.name, fillin_category_path(cat) %>
                        </td>
                        <td>
                          <%= link_to "+ Add Card", new_fillin_card_path(fillin_domain_id: domain, fillin_category_id: cat), class: "btn btn-sm btn-success float-right" %>
                        </td>
                      </tr>
                    </tbody>
                  </table>
              </div>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/fillin_cards/new.html.erb
<h1>New Fillin Card</h1>

<%= render 'form', fillin_card: @fillin_card %>

<%= link_to 'Back', fillin_cards_path %>

app/views/fillin_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Domain:</strong>
  <%= @fillin_card.fillin_domain.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @fillin_card.fillin_category.name %>
</p>


<h3 class="text-primary">Question</h2>
<div class="card">
  <div class="card-body">
      <%= @fillin_card.question %>
  </div>
</div>

<br>

<h3 class="text-info">Additional Info</h2>
<div class="card">
  <div class="card-body">
      <%= @fillin_card.additional_info %>
  </div>
</div>





<%= link_to 'Edit', edit_fillin_card_path(@fillin_card) %> |
<%= link_to 'Back to Fillin Category', fillin_category_path(@fillin_card.fillin_category) %>

<br><br>